name: dbt_taxi_weather
version: "1.0.0"
config-version: 2
profile: dbt_taxi_weather
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  weather_match_rate_threshold: 0.95

models:
  dbt_taxi_weather:
    staging:
      +materialized: view
      +schema: silver
    intermediate:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold